services:
  # 伺服器服務
  mc:
    image: itzg/minecraft-server
    container_name: "mc-cheese"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      # 指定有權限管理的使用者
      UID: 1004
      VERSION: 1.21
      # 自動同意伺服器的EULA
      EULA: "TRUE"
      # 設定分配8GB RAM
      MEMORY: "8G"
      # 設定JVM啟動參數，設定最多使用75% RAM
      JVM_OPTS: "-XX:MaxRAMPercentage=75"
    volumes:
      # 在目前的目錄新增存放資料的目錄
      - ./data:/data

  restore-backup:
    # 同 mc 服務的 image
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      # 必須與 mc 服務掛載相同資料夾，但需要是可寫的
      - ./data:/data
      # 必須與 backups 服務掛載相同資料夾，可以是唯讀的
      - ./mc-backups:/backups:ro

  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      # 由於已經判定伺服器已建立，所以不需要初始化延遲等待
      INITIAL_DELAY: 0
      PRUNE_BACKUPS_DAYS: 3
      PAUSE_IF_NO_PLAYERS: "true"
    volumes:
      - ./data:/data:ro
      - ./mc-backups:/backups
